#!/usr/bin/env python
import sys, os
if len(sys.argv) <= 1:
    print "ERROR: Please pass your DESY UNIX user name."
    sys.exit(1)
else:
    username = sys.argv[1]
    directory = "~/flash_mnt"
    if not os.path.exists(directory):
	os.makedirs(directory)
    cmd = "ssh -f %s@bastion -L 2222:max-cfel002:22 -N" % username
    print cmd
    os.system(cmd)
    cmd = "sshfs -p 2222 %s@localhost:/ %s" % (username, directory)
    print cmd
    os.system(cmd)
    
