#!/usr/bin/env python
import os
this_dir = os.path.dirname(os.path.realpath(__file__))
cmd = "mpirun -n 4 %s/../../hummingbird.py -b example_amo86615.py --lcls-run-number 194 --lcls-number-of-frames 100" % this_dir
print cmd
os.system(cmd)
